/* Generated by Yosys 0.56 (git sha1 9c447ad9d4b1ea589369364eea38b4d70da2c599, x86_64-w64-mingw32-g++ 15.2.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

(* top =  1  *)
(* src = "rtl/counter_7seg.v:1.1-42.10" *)
module counter_7seg(clk, rst_n, up_down, count, seg);
  wire [1:0] _00_;
  wire [1:0] _01_;
  wire _02_;
  wire _03_;
  wire [3:0] _04_;
  wire [3:0] _05_;
  wire [3:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/counter_7seg.v:17.30-17.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _07_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/counter_7seg.v:17.30-17.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _08_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/counter_7seg.v:17.30-17.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _09_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _10_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _11_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _12_;
  (* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:286.27-286.69|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:240.19-240.41" *)
  wire _13_;
  (* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:286.27-286.69|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:248.19-248.41" *)
  wire _14_;
  (* src = "rtl/counter_7seg.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "rtl/counter_7seg.v:5.22-5.27" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "rtl/counter_7seg.v:3.16-3.21" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/counter_7seg.v:6.22-6.25" *)
  output [6:0] seg;
  wire [6:0] seg;
  (* src = "rtl/counter_7seg.v:4.16-4.23" *)
  input up_down;
  wire up_down;
  (* full_case = 32'd1 *)
  (* src = "rtl/counter_7seg.v:28.9-40.16" *)
  reg [6:0] \$auto$proc_rom.cc:155:do_switch$9  [15:0];
  initial begin
    \$auto$proc_rom.cc:155:do_switch$9 [0] = 7'h3f;
    \$auto$proc_rom.cc:155:do_switch$9 [1] = 7'h06;
    \$auto$proc_rom.cc:155:do_switch$9 [2] = 7'h5b;
    \$auto$proc_rom.cc:155:do_switch$9 [3] = 7'h4f;
    \$auto$proc_rom.cc:155:do_switch$9 [4] = 7'h66;
    \$auto$proc_rom.cc:155:do_switch$9 [5] = 7'h6d;
    \$auto$proc_rom.cc:155:do_switch$9 [6] = 7'h7d;
    \$auto$proc_rom.cc:155:do_switch$9 [7] = 7'h07;
    \$auto$proc_rom.cc:155:do_switch$9 [8] = 7'h7f;
    \$auto$proc_rom.cc:155:do_switch$9 [9] = 7'h6f;
    \$auto$proc_rom.cc:155:do_switch$9 [10] = 7'h00;
    \$auto$proc_rom.cc:155:do_switch$9 [11] = 7'h00;
    \$auto$proc_rom.cc:155:do_switch$9 [12] = 7'h00;
    \$auto$proc_rom.cc:155:do_switch$9 [13] = 7'h00;
    \$auto$proc_rom.cc:155:do_switch$9 [14] = 7'h00;
    \$auto$proc_rom.cc:155:do_switch$9 [15] = 7'h00;
  end
  assign seg = \$auto$proc_rom.cc:155:do_switch$9 [count];
  (* src = "rtl/counter_7seg.v:9.5-25.8" *)
  always @(posedge clk)
    if (!rst_n) count[0] <= 1'h0;
    else count[0] <= _06_[0];
  (* src = "rtl/counter_7seg.v:9.5-25.8" *)
  always @(posedge clk)
    if (!rst_n) count[1] <= 1'h0;
    else count[1] <= _06_[1];
  (* src = "rtl/counter_7seg.v:9.5-25.8" *)
  always @(posedge clk)
    if (!rst_n) count[2] <= 1'h0;
    else count[2] <= _06_[2];
  (* src = "rtl/counter_7seg.v:9.5-25.8" *)
  always @(posedge clk)
    if (!rst_n) count[3] <= 1'h0;
    else count[3] <= _06_[3];
  assign _11_[3] = ~count[3];
  assign _11_[2] = ~count[2];
  assign _00_[0] = _08_[0] |(* src = "rtl/counter_7seg.v:14.21-14.34" *)  count[1];
  assign _00_[1] = count[2] |(* src = "rtl/counter_7seg.v:14.21-14.34" *)  _11_[3];
  assign _03_ = _00_[0] |(* src = "rtl/counter_7seg.v:14.21-14.34" *)  _00_[1];
  assign _01_[0] = count[0] |(* src = "rtl/counter_7seg.v:19.21-19.34" *)  count[1];
  assign _01_[1] = count[2] |(* src = "rtl/counter_7seg.v:19.21-19.34" *)  count[3];
  assign _02_ = _01_[0] |(* src = "rtl/counter_7seg.v:19.21-19.34" *)  _01_[1];
  assign _04_[0] = _02_ ? (* src = "rtl/counter_7seg.v:19.21-19.34|rtl/counter_7seg.v:19.17-22.43" *) _08_[0] : 1'h1;
  assign _04_[1] = _02_ ? (* src = "rtl/counter_7seg.v:19.21-19.34|rtl/counter_7seg.v:19.17-22.43" *) _12_[1] : 1'h0;
  assign _04_[2] = _02_ ? (* src = "rtl/counter_7seg.v:19.21-19.34|rtl/counter_7seg.v:19.17-22.43" *) _12_[2] : 1'h0;
  assign _04_[3] = _02_ ? (* src = "rtl/counter_7seg.v:19.21-19.34|rtl/counter_7seg.v:19.17-22.43" *) _12_[3] : 1'h1;
  assign _05_[0] = _03_ ? (* src = "rtl/counter_7seg.v:14.21-14.34|rtl/counter_7seg.v:14.17-17.43" *) _08_[0] : 1'h0;
  assign _05_[1] = _03_ ? (* src = "rtl/counter_7seg.v:14.21-14.34|rtl/counter_7seg.v:14.17-17.43" *) _09_[1] : 1'h0;
  assign _05_[2] = _03_ ? (* src = "rtl/counter_7seg.v:14.21-14.34|rtl/counter_7seg.v:14.17-17.43" *) _09_[2] : 1'h0;
  assign _05_[3] = _03_ ? (* src = "rtl/counter_7seg.v:14.21-14.34|rtl/counter_7seg.v:14.17-17.43" *) _09_[3] : 1'h0;
  assign _06_[0] = up_down ? (* src = "rtl/counter_7seg.v:13.17-13.24|rtl/counter_7seg.v:13.13-23.16" *) _05_[0] : _04_[0];
  assign _06_[1] = up_down ? (* src = "rtl/counter_7seg.v:13.17-13.24|rtl/counter_7seg.v:13.13-23.16" *) _05_[1] : _04_[1];
  assign _06_[2] = up_down ? (* src = "rtl/counter_7seg.v:13.17-13.24|rtl/counter_7seg.v:13.13-23.16" *) _05_[2] : _04_[2];
  assign _06_[3] = up_down ? (* src = "rtl/counter_7seg.v:13.17-13.24|rtl/counter_7seg.v:13.13-23.16" *) _05_[3] : _04_[3];
  assign _08_[0] = ~(* src = "rtl/counter_7seg.v:17.30-17.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:279.31-279.37" *) count[0];
  assign _11_[1] = ~(* src = "rtl/counter_7seg.v:17.30-17.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:279.31-279.37" *) count[1];
  assign _09_[1] = count[1] ^(* src = "rtl/counter_7seg.v:17.30-17.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:289.13-289.25" *)  count[0];
  assign _09_[2] = count[2] ^(* src = "rtl/counter_7seg.v:17.30-17.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:289.13-289.25" *)  _07_[1];
  assign _09_[3] = count[3] ^(* src = "rtl/counter_7seg.v:17.30-17.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:289.13-289.25" *)  _07_[2];
  assign _12_[1] = _11_[1] ^(* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:289.13-289.25" *)  count[0];
  assign _12_[2] = _11_[2] ^(* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:289.13-289.25" *)  _10_[1];
  assign _12_[3] = _11_[3] ^(* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:289.13-289.25" *)  _10_[2];
  assign _07_[1] = count[1] &(* src = "rtl/counter_7seg.v:17.30-17.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:286.27-286.69|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:240.19-240.41" *)  count[0];
  assign _07_[2] = count[2] &(* src = "rtl/counter_7seg.v:17.30-17.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:286.27-286.69|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:248.19-248.41" *)  _07_[1];
  assign _13_ = _11_[1] &(* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:286.27-286.69|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:240.19-240.41" *)  count[0];
  assign _14_ = _11_[2] &(* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:286.27-286.69|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:248.19-248.41" *)  _10_[1];
  assign _10_[1] = count[1] |(* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:286.27-286.69|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:240.12-240.41" *)  _13_;
  assign _10_[2] = count[2] |(* src = "rtl/counter_7seg.v:22.30-22.42|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:286.27-286.69|D:\\msys64\\ucrt64\\bin\\../share/yosys/techmap.v:248.12-248.41" *)  _14_;
  assign _07_[0] = count[0];
  assign _08_[3:1] = count[3:1];
  assign _09_[0] = _08_[0];
  assign _10_[0] = count[0];
  assign _11_[0] = count[0];
  assign _12_[0] = _08_[0];
endmodule
